"""Adicionando campo sexo para bichos

Revision ID: 4e9ee9b56801
Revises: 
Create Date: 2024-12-03 16:04:03.451789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e9ee9b56801'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bicho', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sexo', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bicho', schema=None) as batch_op:
        batch_op.drop_column('sexo')

    # ### end Alembic commands ###
