"""Mudando o campo tipo pra integral

Revision ID: 6ff767fb6749
Revises: c674acbe9c32
Create Date: 2024-11-21 10:34:38.916941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ff767fb6749'
down_revision = 'c674acbe9c32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ong', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=mysql.VARCHAR(length=3),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=mysql.VARCHAR(length=7),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=7),
               existing_nullable=False)

    with op.batch_alter_table('ong', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=3),
               existing_nullable=False)

    # ### end Alembic commands ###
