"""Adicionando campo de senha

Revision ID: 851c2728a22f
Revises: 
Create Date: 2024-11-13 18:03:51.689208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '851c2728a22f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.drop_column('senha_hash')

    # ### end Alembic commands ###
