"""Adicionando campo de CEP

Revision ID: 87eca19e7410
Revises: 3ba3ff431362
Create Date: 2024-11-20 21:56:07.462581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87eca19e7410'
down_revision = '3ba3ff431362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ong', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CEP', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ong', schema=None) as batch_op:
        batch_op.drop_column('CEP')

    # ### end Alembic commands ###
