"""Initial migration

Revision ID: 923112c29a22
Revises: 
Create Date: 2024-11-13 13:30:54.145866

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '923112c29a22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ong')
    op.drop_table('bicho')
    op.drop_table('adocao')
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_nasc', sa.Date(), nullable=False))
        batch_op.drop_column('data_Nasc')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_Nasc', sa.DATE(), nullable=False))
        batch_op.drop_column('data_nasc')

    op.create_table('adocao',
    sa.Column('ID_adocao', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ID_bicho', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ID_usuario', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Data_Adocao', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['ID_bicho'], ['bicho.ID_bicho'], name='adocao_ibfk_1'),
    sa.ForeignKeyConstraint(['ID_usuario'], ['pessoa.ID_usuario'], name='adocao_ibfk_2'),
    sa.PrimaryKeyConstraint('ID_adocao'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('bicho',
    sa.Column('ID_bicho', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Nome', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Especie', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('Idade', mysql.TINYINT(), autoincrement=False, nullable=True),
    sa.Column('Porte', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('Descricao', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('ID_usuario', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ID_ONG', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ID_ONG'], ['ong.ID_ONG'], name='bicho_ibfk_2'),
    sa.ForeignKeyConstraint(['ID_usuario'], ['pessoa.ID_usuario'], name='bicho_ibfk_1'),
    sa.PrimaryKeyConstraint('ID_bicho'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ong',
    sa.Column('ID_ONG', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Nome', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Email', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Telefone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('Endereco', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Bairro', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('Cidade', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('UF', mysql.CHAR(length=2), nullable=True),
    sa.Column('CNPJ', mysql.VARCHAR(length=15), nullable=True),
    sa.PrimaryKeyConstraint('ID_ONG'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
