"""Corrigindo campos CEP e CNPJ

Revision ID: b62a2b0fd896
Revises: 6ff767fb6749
Create Date: 2024-11-23 15:36:32.769903

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b62a2b0fd896'
down_revision = '6ff767fb6749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ong', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('CEP',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=9),
               existing_nullable=False)
        batch_op.alter_column('CNPJ',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=18),
               existing_nullable=False)

    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('ong', schema=None) as batch_op:
        batch_op.alter_column('CNPJ',
               existing_type=sa.String(length=18),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=False)
        batch_op.alter_column('CEP',
               existing_type=sa.String(length=9),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('tipo',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
