"""Adicionando o campo tipo

Revision ID: c674acbe9c32
Revises: 89a19bc774ee
Create Date: 2024-11-21 10:26:22.390040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c674acbe9c32'
down_revision = '89a19bc774ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ong', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=3), nullable=False))

    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=7), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    with op.batch_alter_table('ong', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
